"""empty message

Revision ID: ef6a267bbb71
Revises: cc3aff33354c
Create Date: 2023-09-19 15:50:01.861776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6a267bbb71'
down_revision: Union[str, None] = 'cc3aff33354c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_image', sa.Column('image_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_image', 'image_size')
    # ### end Alembic commands ###
